# Generated by Django 6.0.3 on 2026-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=500, verbose_name='Входная строка')),
                ('detected_bugs', models.JSONField(default=list, verbose_name='Найденные баги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
